spring:
  datasource:
    url: jdbc:mysql://8.129.214.243:3306/mubiao?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: yang
    password: Abcd1234@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1
    dbcp2:
      　　min-idle: 5         #数据库连接池的最小维持连接数
      　　initial-size: 5     #初始化提供的连接数
      　　max-total: 5          #最大的连接数
      　　max-wait-millis: 200        #等待连接获取的最大超时时间

  application:
    name: orm
  resources:
    static-locations: [ "classpath:/Lib/" ]
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lmb.orm.entity
  type-handlers-package: com.lmb.orm.handler
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delete

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  metrics:
    export:
      prometheus:
        enabled: true
