server:
  port: 18084

spring:
  application:
    name: nacos-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gateway-service
          uri: lb://web
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1
        - id: orm-service
          uri: lb://orm
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0
    nacos:
      discovery:
        server-addr: 211.159.184.140:8848